## Task 01

In [2]:
import numpy as np
#for the integers
integers=np.random.randint(1,10,10)
floats=np.random.random(10)
print("Shape: ",integers.shape, "\nIntegers: ",integers)

#for the floats
floats=np.random.random(10)
print("Shape: ",floats.shape, "\nFloats: ",floats)

Shape:  (10,) 
Integers:  [6 6 3 9 2 1 4 5 2 3]
Shape:  (10,) 
Floats:  [0.09076685 0.32818482 0.97393387 0.71091689 0.37100698 0.15108787
 0.54927216 0.17484365 0.33437876 0.75173197]


In [214]:
chars = np.chararray((3, 3))
chars[:]='abc'
print("Shape: ",chars.shape, "\nChars: ", chars)

Shape:  (3, 3) 
Chars:  [[b'a' b'a' b'a']
 [b'a' b'a' b'a']
 [b'a' b'a' b'a']]


## Task 02

In [4]:
# array of zeros
arr=np.zeros(10, dtype=int)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# np.empty
ap=np.empty(10)
ap

array([0.09076685, 0.32818482, 0.97393387, 0.71091689, 0.37100698,
       0.15108787, 0.54927216, 0.17484365, 0.33437876, 0.75173197])

In [6]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [218]:
# np.fill
array=np.array([1,2])
array.fill(0)
print(array)

[0 0]


In [219]:
# np.full
np.full((3,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

## Task 03

#### when numpy array is declared as object, we can create an array with different data-types elements

## Task 04

In [220]:
# np.linspace
arr=np.linspace(5,15)
arr.shape

(50,)

# Task 05

In [239]:
# np.arange
arr=np.arange(1,100)
arr.shape

(99,)

# Task 06

In [235]:
# # np.reshape
# arr.reshape(100, 15)
# # No its not possible

# Task 07

In [236]:
# arr=np.reshape(arr, (100, 10))

In [7]:
arr=[[1, 2, 3], [4, 5, 6], [ 7, 8, 9]]
print("Along X-axis: ", np.sum(arr, axis=0))
print("Along Y-axis: ", np.sum(arr, axis=1))

Along X-axis:  [12 15 18]
Along Y-axis:  [ 6 15 24]


In [240]:
arr.flatten()

print(arr, arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99] (99,)


In [241]:
# np.ravel

arr=arr.ravel()

print(arr, arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99] (99,)


In [242]:
# np.nbytes

print(arr.nbytes)

396


In [228]:
# np.max

np.max(arr)

9

In [229]:
# np.min

np.min(arr)

1

In [230]:
# np.sort

np.sort(arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [195]:
# np.multiply

np.multiply(arr, arr)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [196]:
# np.sqrt

np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [197]:
# np.linalg.norm

np.linalg.norm(arr)

16.881943016134134

In [198]:
# np.mean

np.mean(arr)

5.0

In [199]:
# np.std

np.std(arr)

2.581988897471611

In [200]:
# integers

arr=np.random.randint(0,10,10)
arr

array([4, 6, 6, 2, 0, 0, 8, 4, 1, 9])

In [201]:
# checking if theres no zero

np.any((arr))

True

In [202]:
# checking if theres zero

np.all(arr)

False

In [203]:
# some angles
in_array = np.arange(10.) * 90
print ("Degree values : \n", in_array)


# angles to radians
radian_Values = np.radians(in_array)
print ("\nRadian values : \n", radian_Values)

Degree values : 
 [  0.  90. 180. 270. 360. 450. 540. 630. 720. 810.]

Radian values : 
 [ 0.          1.57079633  3.14159265  4.71238898  6.28318531  7.85398163
  9.42477796 10.99557429 12.56637061 14.13716694]


In [204]:
arr=np.arange(10.) *90
arr2=np.radians(arr)
print("Angles: ",arr, "\nRadians: ", arr2)

# radians to degrees

print("\nAngles: ",np.degrees(arr2))

Angles:  [  0.  90. 180. 270. 360. 450. 540. 630. 720. 810.] 
Radians:  [ 0.          1.57079633  3.14159265  4.71238898  6.28318531  7.85398163
  9.42477796 10.99557429 12.56637061 14.13716694]

Angles:  [  0.  90. 180. 270. 360. 450. 540. 630. 720. 810.]


In [205]:
# savetxt
arr= np.array([1, 2, 3, 4])
np.savetxt('file.txt', a, fmt='%d')

# loadttxt

b = np.loadtxt('file.txt', dtype=int)
print(a, "\n", b)

[0.09867556 0.1121841  0.09364668 0.33659482 0.77946018 0.47490001
 0.65640341 0.60678995 0.73557598 0.65492766] 
 [0 0 0 0 0 0 0 0 0 0]


## np.random.normal

In [206]:
mu, sigma=0, 0.1
arr=np.random.normal(mu, sigma, (3,3,12,3))

array([[[[-0.04443771,  0.00191855, -0.02060454],
         [ 0.0180607 ,  0.08199442,  0.02061188],
         [ 0.00539026, -0.08195938, -0.02175964],
         [-0.11905382, -0.15957909,  0.10128804],
         [ 0.09167202,  0.09517687, -0.14124052],
         [-0.02475733,  0.01927433,  0.17647346],
         [-0.04509637,  0.05472871, -0.14015611],
         [-0.06935199, -0.12274073, -0.09671359],
         [ 0.1026377 , -0.0013289 , -0.09631576],
         [-0.06043843,  0.06739933,  0.02649126],
         [-0.00248889, -0.14394938, -0.03597004],
         [ 0.10279707,  0.02833923,  0.07302277]],

        [[ 0.0979243 , -0.16360364, -0.07102229],
         [-0.01407601,  0.00341741,  0.12479056],
         [ 0.03189154,  0.0779872 ,  0.01236481],
         [-0.10018465,  0.25658586,  0.20399316],
         [-0.06999988, -0.06588168, -0.01691876],
         [ 0.13164429, -0.02389274,  0.01347818],
         [ 0.06175893,  0.0037295 , -0.11438206],
         [-0.11834681,  0.23136262, -0.05391249]

In [243]:
np.mean(arr)

50.0

In [244]:
np.std(arr)

28.577380332470412

In [245]:
np.var(arr)

816.6666666666666

In [246]:
np.max(arr)

99

In [247]:
np.min(arr)

1