# TASK1

In [8]:
A = [[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9,10,11,12]]
 
# take a 3x4 matrix   
B = [[1,0,3,4],
    [5,6,1,8],
    [0,0,0, 12]]
     
result = [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]
 
# iterating by row of A
for i in range(len(A)):
 
    # iterating by column by B
    for j in range(len(B[0])):
 
        # iterating by rows of B
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]
 
for r in result:
    print(r)

[11, 12, 5, 56]
[35, 36, 21, 152]
[59, 60, 37, 248]


In [23]:
r1 = int(input("Enter number of row for Matrix A :"))
c1 = int(input("Enter number of column for Matrix A :"))
r2 = int(input("Enter number of row for Matrix B :"))
c2 = int(input("Enter number of column for Matrix B :"))


print("Enter element row wise for matrix A :")
A = []
for i in range(r1):
    arrA = []
    for j in range(c1):
        arrA.append(int(input()))
    A.append(arrA)

print("Enter element row wise for matrix B :")
B = []
for i in range(r2):
    arrB = []
    for j in range(c2):
        arrB.append(int(input()))
    B.append(arrB)

if c1 != r2:
   print("\nCan't Multiply --> To Multiply two matrix (A x B) ,Column of Matrix A = Row of Matrix B")
   B = np.array(B)
   B = np.transpose(B)
   print("Matrix A=")
   for w in A:
       print(w)
   print("matrix B=")
   for x in B:
       print(x)
   result = []
   for i in range(r1):
       arrR = []
       for j in range(c2):
           arrR.append(0)
       result.append(arrR)
   for i in range(len(A)):
       for j in range(len(B[0])):
           for k in range(len(B)):
               result[i][j] = A[i][k] * B[k][j] + result[i][j]

   print("AXB=")
   for y in result:
      print(y)   

Enter number of row for Matrix A :3
Enter number of column for Matrix A :4
Enter number of row for Matrix B :3
Enter number of column for Matrix B :4
Enter element row wise for matrix A :
1
2
3
4
5
6
7
8
9
10
11
12
Enter element row wise for matrix B :
1
0
3
4
5
6
1
8
0
0
0
12

Can't Multiply --> To Multiply two matrix (A x B) ,Column of Matrix A = Row of Matrix B
Matrix A=
[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]
matrix B=
[1 5 0]
[0 6 0]
[3 1 0]
[ 4  8 12]
AXB=
[26, 52, 48, 0]
[58, 132, 96, 0]
[90, 212, 144, 0]


# task2

In [13]:
Fav_food_items = [["pizza","burger","hotdogs"] , ["pasta","hotdogs"],["pizza"],["burger","hotdogs"],["rice" ,"pasta"] ,["pasta"]]
list=[]
list1=[]
final=[]
for i in range(0,6):
    list.append(i)
    
for i in range(0,len(Fav_food_items)):
    x = set(Fav_food_items[i])

    for j in range(0,len(Fav_food_items)):
        y = set(Fav_food_items[j])
        if i!=j:
            if (x.issubset(y)):
                list1.append(i)

for i in list:
    if i not in list1:
        final.append(i)

In [14]:
print(final)

[0, 1, 4]


# task3 

In [18]:
Data = [{"roll_no": "i11-1001", "marks": {"english": (1.4, 2.5, 15, 9.6, 33), "calculus": (2.4, 1.5, 12, 1.6, 21)}, "attendance": 88.4 }, {"roll_no": "i11-1002", "marks": {"english": (2.4, 1.5, 12, 1.6, 21),"programming fundaments": (2.4, 1.5, 12, 1.6, 21)}, "attendance": 79.4 }, {"roll_no": "i11-1003", "marks": {"calculus": (2.4, 1.5, 12, None, 21),"programming fundamentals": (2.4, 1.5, 12, 1.6, 21)}, "attendance": 79.4 }]
print(Data)

[{'roll_no': 'i11-1001', 'marks': {'english': (1.4, 2.5, 15, 9.6, 33), 'calculus': (2.4, 1.5, 12, 1.6, 21)}, 'attendance': 88.4}, {'roll_no': 'i11-1002', 'marks': {'english': (2.4, 1.5, 12, 1.6, 21), 'programming fundaments': (2.4, 1.5, 12, 1.6, 21)}, 'attendance': 79.4}, {'roll_no': 'i11-1003', 'marks': {'calculus': (2.4, 1.5, 12, None, 21), 'programming fundamentals': (2.4, 1.5, 12, 1.6, 21)}, 'attendance': 79.4}]


In [19]:
roll_no= []
sa=[]
button=[]
sol=[]
keys={}
kas={}
sums=0
for i in Data:
    roll_no.append(i['roll_no'])
    for key,val in i['marks'].items():
        button.append(key)
        for j in range(len(val)):
            if(val[j] != None):
                sums=sums+val[j]
        sol.append(sums)
        kas[key]=sums
    keys[i['roll_no']]=kas

keys

{'i11-1001': {'english': 138.5,
  'calculus': 213.9,
  'programming fundaments': 177.0,
  'programming fundamentals': 252.4},
 'i11-1002': {'english': 138.5,
  'calculus': 213.9,
  'programming fundaments': 177.0,
  'programming fundamentals': 252.4},
 'i11-1003': {'english': 138.5,
  'calculus': 213.9,
  'programming fundaments': 177.0,
  'programming fundamentals': 252.4}}

# task4

In [15]:
import pandas as pd

In [33]:
temp = pd.read_csv("Students_Dataset.csv")
temp

Sr. No     Semester Course Code                           Course Title  \
0           0    Fall 2016       SS101                       English Language   
1           0  Spring 2017       SS122                    English Composition   
2           0    Fall 2016       SL101                   English Language Lab   
3           0  Spring 2017       EE182                      Basic Electronics   
4           0  Spring 2017       MT119       Calculus and Analytical Geometry   
...       ...          ...         ...                                    ...   
40763    1779      Unknown       SS111          Islamic and Religious Studies   
40764    1779      Unknown       SS113                       Pakistan Studies   
40765    1779      Unknown       SS122                    English Composition   
40766    1779      Unknown       SS150  English Composition and Comprehension   
40767    1779      Unknown       SS152    Communication & Presentation Skills   

       Credit Hours Grade  Grade Point  SGPA  CGPA  Warning  
0                 3    A-         3.67  0.82  0.82        2  
1                 3     B         3.00  1.00  1.50        2  
2                 1     B         3.00  0.82  0.82        2  
3                 3     D         1.00  1.00  1.50        2  
4                 3    D+         1.33  1.00  1.50        2  
...             ...   ...          ...   ...   ...      ...  
40763             3    UK        -1.00  0.00  0.00        0  
40764             3    UK        -1.00  0.00  0.00        0  
40765             3    UK        -1.00  0.00  0.00        0  
40766             2    UK        -1.00  0.00  0.00        0  
40767             2    UK        -1.00  0.00  0.00        0  

[40768 rows x 10 columns]

In [34]:
temp=temp.drop('Semester',axis=1)
temp=temp.drop('Grade',axis=1)
temp=temp.drop('SGPA',axis=1)
temp=temp.drop('Course Title',axis=1)
temp=temp.drop('Credit Hours',axis=1)
temp

Sr. No Course Code  Grade Point  CGPA  Warning
0           0       SS101         3.67  0.82        2
1           0       SS122         3.00  1.50        2
2           0       SL101         3.00  0.82        2
3           0       EE182         1.00  1.50        2
4           0       MT119         1.33  1.50        2
...       ...         ...          ...   ...      ...
40763    1779       SS111        -1.00  0.00        0
40764    1779       SS113        -1.00  0.00        0
40765    1779       SS122        -1.00  0.00        0
40766    1779       SS150        -1.00  0.00        0
40767    1779       SS152        -1.00  0.00        0

[40768 rows x 5 columns]

In [ ]:
temp1=temp[Coursecode].unique()
temp1